# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/avitohol/Desktop/Thesis/NSFEM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/avitohol/Desktop/Thesis/NSFEM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avitohol/Desktop/Thesis/NSFEM/CMakeFiles /home/avitohol/Desktop/Thesis/NSFEM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avitohol/Desktop/Thesis/NSFEM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

assemble/assemble.o: assemble/assemble.cpp.o
.PHONY : assemble/assemble.o

# target to build an object file
assemble/assemble.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/assemble/assemble.cpp.o
.PHONY : assemble/assemble.cpp.o

assemble/assemble.i: assemble/assemble.cpp.i
.PHONY : assemble/assemble.i

# target to preprocess a source file
assemble/assemble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/assemble/assemble.cpp.i
.PHONY : assemble/assemble.cpp.i

assemble/assemble.s: assemble/assemble.cpp.s
.PHONY : assemble/assemble.s

# target to generate assembly for a file
assemble/assemble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/assemble/assemble.cpp.s
.PHONY : assemble/assemble.cpp.s

basis/lagrange_p1_triangle.o: basis/lagrange_p1_triangle.cpp.o
.PHONY : basis/lagrange_p1_triangle.o

# target to build an object file
basis/lagrange_p1_triangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/basis/lagrange_p1_triangle.cpp.o
.PHONY : basis/lagrange_p1_triangle.cpp.o

basis/lagrange_p1_triangle.i: basis/lagrange_p1_triangle.cpp.i
.PHONY : basis/lagrange_p1_triangle.i

# target to preprocess a source file
basis/lagrange_p1_triangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/basis/lagrange_p1_triangle.cpp.i
.PHONY : basis/lagrange_p1_triangle.cpp.i

basis/lagrange_p1_triangle.s: basis/lagrange_p1_triangle.cpp.s
.PHONY : basis/lagrange_p1_triangle.s

# target to generate assembly for a file
basis/lagrange_p1_triangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/basis/lagrange_p1_triangle.cpp.s
.PHONY : basis/lagrange_p1_triangle.cpp.s

geometry/affine.o: geometry/affine.cpp.o
.PHONY : geometry/affine.o

# target to build an object file
geometry/affine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geometry/affine.cpp.o
.PHONY : geometry/affine.cpp.o

geometry/affine.i: geometry/affine.cpp.i
.PHONY : geometry/affine.i

# target to preprocess a source file
geometry/affine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geometry/affine.cpp.i
.PHONY : geometry/affine.cpp.i

geometry/affine.s: geometry/affine.cpp.s
.PHONY : geometry/affine.s

# target to generate assembly for a file
geometry/affine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/geometry/affine.cpp.s
.PHONY : geometry/affine.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

mesh/parser.o: mesh/parser.cpp.o
.PHONY : mesh/parser.o

# target to build an object file
mesh/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mesh/parser.cpp.o
.PHONY : mesh/parser.cpp.o

mesh/parser.i: mesh/parser.cpp.i
.PHONY : mesh/parser.i

# target to preprocess a source file
mesh/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mesh/parser.cpp.i
.PHONY : mesh/parser.cpp.i

mesh/parser.s: mesh/parser.cpp.s
.PHONY : mesh/parser.s

# target to generate assembly for a file
mesh/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mesh/parser.cpp.s
.PHONY : mesh/parser.cpp.s

quadrature/quadrature.o: quadrature/quadrature.cpp.o
.PHONY : quadrature/quadrature.o

# target to build an object file
quadrature/quadrature.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/quadrature/quadrature.cpp.o
.PHONY : quadrature/quadrature.cpp.o

quadrature/quadrature.i: quadrature/quadrature.cpp.i
.PHONY : quadrature/quadrature.i

# target to preprocess a source file
quadrature/quadrature.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/quadrature/quadrature.cpp.i
.PHONY : quadrature/quadrature.cpp.i

quadrature/quadrature.s: quadrature/quadrature.cpp.s
.PHONY : quadrature/quadrature.s

# target to generate assembly for a file
quadrature/quadrature.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/quadrature/quadrature.cpp.s
.PHONY : quadrature/quadrature.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... assemble/assemble.o"
	@echo "... assemble/assemble.i"
	@echo "... assemble/assemble.s"
	@echo "... basis/lagrange_p1_triangle.o"
	@echo "... basis/lagrange_p1_triangle.i"
	@echo "... basis/lagrange_p1_triangle.s"
	@echo "... geometry/affine.o"
	@echo "... geometry/affine.i"
	@echo "... geometry/affine.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mesh/parser.o"
	@echo "... mesh/parser.i"
	@echo "... mesh/parser.s"
	@echo "... quadrature/quadrature.o"
	@echo "... quadrature/quadrature.i"
	@echo "... quadrature/quadrature.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

